/*
 * AveriasUI.java
 *
 * Created on 2 de septiembre de 2008, 7:08
 */

package mi.parque;
import javax.swing.*;

/**
 *
 * @author  owner
 */
public class AveriasUI extends javax.swing.JPanel {

    /** Creates new form AveriasUI */
    public AveriasUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        averiar_vehiculos = new javax.swing.JButton();
        averiar_coches = new javax.swing.JButton();
        reparar_vehiculos = new javax.swing.JButton();
        reparar_coches = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Averías", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        averiar_vehiculos.setText("Averiar vehículo(s) de la noria");
        averiar_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averiar_vehiculosActionPerformed(evt);
            }
        });

        averiar_coches.setText("Averiar coche(s) de la montaña rusa");
        averiar_coches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averiar_cochesActionPerformed(evt);
            }
        });

        reparar_vehiculos.setText("Reparar vehículo(s) de la noria");
        reparar_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparar_vehiculosActionPerformed(evt);
            }
        });

        reparar_coches.setText("Reparar coche(s) de la montaña rusa");
        reparar_coches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparar_cochesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(averiar_vehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reparar_vehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(averiar_coches, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reparar_coches, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(averiar_vehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reparar_vehiculos)
                .addGap(11, 11, 11)
                .addComponent(averiar_coches, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(reparar_coches)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void averiar_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averiar_vehiculosActionPerformed
// TODO add your handling code here:
    int vehiculos_averiados = 0;    //este es el contador de cuantos voy averiando
    DatosAveriasUI rec = new DatosAveriasUI();
    if(JOptionPane.showConfirmDialog(this, rec, "Introduzca datos",
    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
    == JOptionPane.OK_OPTION) {
    //Recogida datos RELLENAR
    int numero_averias=rec.numero_averias();
    //Procesamos los datos recogidos
    for (int i=0; i<ParqueUI.noria.vehiculos.size(); i++){
        boolean esta_averiado = ((Vehiculo)ParqueUI.noria.vehiculos.get(i)).averia;
        if (!esta_averiado && vehiculos_averiados<numero_averias){
            ((Vehiculo)ParqueUI.noria.vehiculos.get(i)).inducirAveria();
            //busca operario para reparar
            ParqueUI.cra.busca_operario_noria();
            //aumenta contador de vehiculos averiados
            vehiculos_averiados++;
        }
    }
    ParqueUI.mi_consola.append("Se han producido " + vehiculos_averiados + " averías en la noria\n");
    }
}//GEN-LAST:event_averiar_vehiculosActionPerformed

private void averiar_cochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averiar_cochesActionPerformed
// TODO add your handling code here:
    int coches_averiados = 0;    //este es el contador de cuantos voy averiando
    DatosAveriasUI rec = new DatosAveriasUI();
    if(JOptionPane.showConfirmDialog(this, rec, "Introduzca datos",
    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
    == JOptionPane.OK_OPTION) {
    //Recogida datos RELLENAR
    int numero_averias=rec.numero_averias();
    //Procesamos los datos recogidos
    //En este caso se llega hasta -1 porque el último no tiene a nadie detras
    //para detectar falta de anclaje
    for (int i=0; i<ParqueUI.noria.vehiculos.size()-1; i++){
        boolean esta_averiado = ((Vehiculo)ParqueUI.montania.coches.get(i)).averia;
        if (!esta_averiado && coches_averiados<numero_averias){
            ((Vehiculo)ParqueUI.montania.coches.get(i)).inducirAveria();
            //busca operario para reparar
            ParqueUI.cra.busca_operario_montania();
            //aumenta contador de vehiculos averiados
            coches_averiados++;
        }
    }
    ParqueUI.mi_consola.append("Se han producido " + coches_averiados + " averías en la montaña rusa\n");
    }
}//GEN-LAST:event_averiar_cochesActionPerformed

private void reparar_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparar_vehiculosActionPerformed
// TODO add your handling code here:
    int vehiculos_reparados = 0;    //este es el contador de cuantos voy reparando
    DatosReparacionesUI rec = new DatosReparacionesUI();
    if(JOptionPane.showConfirmDialog(this, rec, "Introduzca datos",
    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
    == JOptionPane.OK_OPTION) {
    //Recogida datos RELLENAR
    int numero_reparados=rec.numero_reparados();
    //Procesamos los datos recogidos
    for (int i=0; i<ParqueUI.noria.vehiculos.size() ;i++){
        boolean esta_averiado=((Vehiculo)ParqueUI.noria.vehiculos.get(i)).averia;
        if (esta_averiado && vehiculos_reparados<numero_reparados){
            ((Vehiculo)ParqueUI.noria.vehiculos.get(i)).repararAveria();
            ParqueUI.cra.libera_operario_noria();
            vehiculos_reparados++;
        }
    }
    ParqueUI.mi_consola.append("Se han producido " + vehiculos_reparados + " reparaciones en la noria\n");
    }
}//GEN-LAST:event_reparar_vehiculosActionPerformed

private void reparar_cochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparar_cochesActionPerformed
// TODO add your handling code here:
    int coches_reparados = 0;    //este es el contador de cuantos voy averiando
    DatosReparacionesUI rec = new DatosReparacionesUI();
    if(JOptionPane.showConfirmDialog(this, rec, "Introduzca datos",
    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
    == JOptionPane.OK_OPTION) {
    //Recogida datos RELLENAR
    int numero_reparados=rec.numero_reparados();
    //Procesamos los datos recogidos
    for (int i=0; i<ParqueUI.montania.coches.size() ;i++){
        boolean esta_averiado=((Vehiculo)ParqueUI.montania.coches.get(i)).averia;
        if (esta_averiado && coches_reparados<numero_reparados){
            ((Vehiculo)ParqueUI.montania.coches.get(i)).repararAveria();
            ParqueUI.cra.libera_operario_montania();
            coches_reparados++;
        }
    }
    ParqueUI.mi_consola.append("Se han producido " + coches_reparados + " reparaciones en la montaña rusa\n");
    }
}//GEN-LAST:event_reparar_cochesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton averiar_coches;
    private javax.swing.JButton averiar_vehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reparar_coches;
    private javax.swing.JButton reparar_vehiculos;
    // End of variables declaration//GEN-END:variables

}
